[project]
name = "strands-agents-handson"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "strands-agents>=1.13.0",
    "strands-agents-builder>=0.1.10",
    "strands-agents-tools>=0.2.12",
]
